# Generated by Django 4.2.19 on 2025-03-08 04:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sproutly', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='plant_images/'),
        ),
        migrations.AddField(
            model_name='plant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='AutoSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watering_enabled', models.BooleanField(default=True)),
                ('watering_amount', models.FloatField()),
                ('humidity_control_enabled', models.BooleanField(default=True)),
                ('humidity_target', models.FloatField()),
                ('lighting_enabled', models.BooleanField(default=True)),
                ('lighting_hours', models.IntegerField()),
                ('temperature_control_enabled', models.BooleanField(default=True)),
                ('temperature_target', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auto_schedule', to='sproutly.plant')),
            ],
        ),
    ]
