# Generated by Django 4.2.19 on 2025-03-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sproutly', '0002_plant_created_at_plant_image_plant_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoschedule',
            name='nutrients_control_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='autoschedule',
            name='nutrients_target',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
